FileStorage.PL/Controllers/SharedFileController.cs
using AutoMapper;
using FileStorage.BLL.Interfaces;
using FileStorage.PL.Models;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FileStorage.PL.Controllers
{
    /// <summary>
    /// SharedFileController, getting shared file, access authorize and anonymous users
    /// </summary>
    [AllowAnonymous]
    public class SharedFileController : Controller
    {
        private readonly ISharedFileService sharedService;

        private readonly IMapper mapper;

        public SharedFileController(ISharedFileService _sharedService, IMapper _mapper)
        {
            sharedService = _sharedService;
            mapper = _mapper;
        }

        public async Task<ActionResult> Index(string link)
        {
            var file = await sharedService.GetSharedFile(link);
            return View(mapper.Map<SharedViewModel>(file));
        }

        [HttpPost]
        public async Task<ActionResult> GetFile(string link)
        {
            var file = await sharedService.GetSharedFile(link);
            if (file != null)
            {
                string file_path = file.Path;
                string file_type = file.Type;
                string file_name = file.Name;
                return File(file_path, file_type, file_name);
            }
            return RedirectToAction("Index");
        }
    }
}

FileStorage.PL/Views/SharedFile/Index.cshtml
@model FileStorage.PL.Models.SharedViewModel
@{
    ViewBag.Title = "Shared File";
}
@using FileStorage.PL.Helpers
@if (Model is null)
{
    <h4>File not found</h4>
}
else
{
    <div class="action-panel">
        <b class="page-title">Shared file</b>
    </div>
    <div class="files-container">
        <div class="file">
            <div class="file-name">@Model.Name</div>
            <div class="file-actions">
                @GetSizeFromBytes.PrintFileSize(Model.Length)
                @using (Html.BeginForm("GetFile", "SharedFile", new { link = Model.SharedLink }, FormMethod.Post, new { target = "frame" }))
                {
                    <div class="file-action" title="Download"><button class="action-form-button" type="submit"><i class="fas fa-download"></i></button></div>
                    <iframe class="download-frame" name="frame" style="display:none"></iframe>
                }
            </div>
        </div>
    </div>
}